version: '3'

services:
  sqlalchemy_helpers:
    build: .
    image: lycantropos/sqlalchemy_helpers:latest
    volumes:
      - .:/sqlalchemy_helpers/
    environment:
      POSTGRES_URI: postgresql://username:password@postgres/sqlalchemy_helpers
      MYSQL_URI: mysql+pymysql://root:secret@mysql
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
    entrypoint: python3
    command: setup.py test

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=sqlalchemy_helpers
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=secret
